2019-04-13 15:20:36,266 ERROR: Exception on /login [GET] [in /Users/gkai/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gkai/Documents/Meitu/meipai/New/LearningInPython/flaskPythonweb/app/routes.py", line 67, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/gkai/Documents/Meitu/meipai/New/LearningInPython/flaskPythonweb/app/templates/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/gkai/Documents/Meitu/meipai/New/LearningInPython/flaskPythonweb/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/gkai/Documents/Meitu/meipai/New/LearningInPython/flaskPythonweb/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/gkai/Documents/Meitu/meipai/New/LearningInPython/flaskPythonweb/app/templates/login.html", line 15, in block "app_content"
    <!--<a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>-->
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/Users/gkai/anaconda3/lib/python3.6/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2019-04-13 15:35:19,885 INFO: Microblog startup [in /Users/gkai/Documents/Meitu/meipai/New/LearningInPython/flaskPythonweb/app/__init__.py:39]
2019-04-13 15:49:48,895 INFO: Microblog startup [in /Users/gkai/Documents/Meitu/meipai/New/LearningInPython/flaskPythonweb/app/__init__.py:39]
2019-04-13 15:50:12,125 INFO: Microblog startup [in /Users/gkai/Documents/Meitu/meipai/New/LearningInPython/flaskPythonweb/app/__init__.py:39]
2019-04-13 18:54:08,487 INFO: Microblog startup [in /Users/gkai/Documents/Meitu/meipai/New/LearningInPython/flaskPythonweb/app/__init__.py:44]
